### ISSUE TITLE
Can I create react version of website?

### ISSUE THREAD

**Issue by vivek80801** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#105]
I have seen this project has three branches. One is main branch, second branch is develop branch and it is made with `sevelt`  and third branch is made with `vuejs`.

So, Can I try to make another version of this project with `reactjs` ?

**Comment by BOLT04** [comment]
Hi @vivek80801 😃, thank you for opening this issue and for having the initiative of contributing with another version of the website, using React.js 👍 👍.
You're more than welcome to make that version, I'll assign this issue to you and then you can submit a PR.

**Comment by eddiejaoude** [comment]
Great idea @vivek80801 👍 - I will create a `react` branch that you can create a PR against. Thanks @BOLT04 👍

**Comment by eddiejaoude** [comment]
There is a `reactjs` branch already - I think @BOLT04 beat me to it 🤓

**Comment by vivek80801** [comment]
@eddiejaoude  and @BOLT04 

It will be great. If I can get some suhggestion from you.

I have created a draft pull request #112 .
