### ISSUE TITLE
reroute `Join Us` button to issue-template(and edits in template)

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#118]
The current `Join Us` button links to the `support` repo [issue section]()
![Screenshot 2020-11-17 at 8 36 17 PM](https://user-images.githubusercontent.com/62864373/99406991-9886fc00-2914-11eb-9c59-c26f89ba3276.png)
Wouldn't it be better if we route people directly to ["Invite me to the organisation" issue](https://github.com/EddieJaoudeCommunity/support/issues/new?assignees=eddiejaoude%2C+mikeysan&labels=invite+me+to+the+organization&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization) ?
This would make it easier and faster to make an invite issue.

Also, there is another change, that can be made in the issue-template...
This is the current template: 
![Screenshot 2020-11-17 at 8 54 18 PM](https://user-images.githubusercontent.com/62864373/99409232-282daa00-2917-11eb-95ff-ba62616d2959.png)
If we comment this out, it would encourage people to make more personalised-> "could I be invited" issue
We can also make the following tweaks for this:
- Comment the paragraph(resulting in issues not containing text, intended for the creator)
- Add a format for asking an invite. Something like this->
```
<!---
Invitation will be sent for the GitHub Organization soon. We look forward to having you part of our community :nerd:

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organization list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practicing:

- Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
- Practice repo, instructions how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
- Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
-->

<!--Some Details-->
Name:

Discord Username(if exists): 
<!--https://discord.gg/ErG8W36Tkm (link to discord server)-->

Additional Context:
<!--Where did you meet Eddie?-->

<!--What do you like about this community/ why do you want to join--> 
```

**Comment by BOLT04** [comment]
> Wouldn't it be better if we route people directly to "Invite me to the organisation" issue ?

Greate idea @Vyvy-vi 👍 👍, changing the URL to the one you said is way better. 

> Comment the paragraph(resulting in issues not containing text, intended for the creator)

I support this 👍 since it would decrease the payload shown on the GitHub notification on the Discord channel 😅. My concern is that people creating the issue don't read it and just discard what is in the template. Currently, that gets added on the issue description so it doesn't go away, but let's hear more opinions of the community 😃

**Comment by eddiejaoude** [comment]
Yes & Yes ❤️

**Comment by Vyvy-vi** [comment]
(I'll have to have a look at the code to find out where this button is attached).
 The issue reformat has to be done in support repo or the community-gh-template repo?

**Comment by BOLT04** [comment]
> (I'll have to have a look at the code to find out where this button is attached).

@Vyvy-vi  the link for the button is here:
https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/51bff86a9b02f15b7ec8809985b9fc57ed57f196/src/App.svelte#L73

> The issue reformat has to be done in support repo or the community-gh-template repo?

I believe the file to change is on the support repo here 😃 : 
https://github.com/EddieJaoudeCommunity/support/blob/main/.github/ISSUE_TEMPLATE/invitation.md

**Comment by Vyvy-vi** [comment]
Thanks 🙂

**Comment by Vyvy-vi** [comment]
I think, that this issue could be closed 🤔 
thoughts?

**Comment by eddiejaoude** [comment]
Yes 👍 , looks like the PR was merged 🤓
