### ISSUE TITLE
our project/repo list, technologies, state (alpha, beta, ...)

### ISSUE THREAD

**Issue by Arvindjitta** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#19]
Initial from https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/5

lets list all of our community projects...

cards should look like this: -
[
![Facebook Post - 1](https://user-images.githubusercontent.com/35035788/91071769-317be300-e656-11ea-8339-9d256373d949.png)
](url)

**Comment by eddiejaoude** [comment]
If you want some inspiration, this site has some good examples https://tailwindcomponents.com

**Comment by Arvindjitta** [comment]
@eddiejaoude brother, which projects does the list should include ....all of your 224 repositories?

**Comment by eddiejaoude** [comment]
Nope, please only include our community organisation repos https://github.com/EddieJaoudeCommunity 

Should be about 8 repos. If you could leave a "section" for project status, dont worry about the value for now, I can fill those in - example values will be `alpha`, `beta` ...

**Comment by Arvindjitta** [comment]
so basically the new should consist of a list in README?? ..should it be like this https://github.com/EddieJaoudeCommunity/awesome-github-profiles

**Comment by eddiejaoude** [comment]
> new repo

not sure what you mean here. It will go in this repo.

I was thinking something like this for the list of projects https://tailwindcomponents.com/component/post-card
- project name
- project description 
- repo link
- website link
- tech list
- status 

*note: with the screenshot, dont make it a small circle, full size square will look better*

**Comment by Arvindjitta** [comment]
i got your vision

**Comment by eddiejaoude** [comment]
Dont worry about making it perfect, do only a little, just enough to add value, then we can iterate on it to make more improvements 😉 (little and often)

**Comment by Arvindjitta** [comment]
i have made a pull request for the card , as of now it only looks great in largscreens

**Comment by eddiejaoude** [comment]
Lets continue the discussion in the PR, so we can keep the discussion in the right place 😉 https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/pull/20

**Comment by BOLT04** [comment]
@Arvindjitta, that UI looks amazing 💯 !!

**Comment by BOLT04** [comment]
@eddiejaoude and @Arvindjitta do you think we can close this issue?
Currently, this UI is being used for the moderator cards and it was done in #21 :
![imagem](https://user-images.githubusercontent.com/18630253/94349667-9b651f00-003e-11eb-8192-f6d696fb2845.png)

**Comment by eddiejaoude** [comment]
Good idea @BOLT04 as this has not moved in a while. 

We will need more cards for other sections, so this can be picked up later on by @Arvindjitta or someone else when they have time.
