### ISSUE TITLE
Update Website screenshot on README.md

### ISSUE THREAD

**Issue by ritvij14** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#31]
The screenshot of the website present on `README.md` needs to be updated since we now have more stuff on our website. This will help the community who come to visit this repository a good idea of our website from the image.

**Comment by Arvindjitta** [comment]
yeah brother, its need to be updates lets make a PR for That

**Comment by VictoryWekwa** [comment]
I can do this

**Comment by VictoryWekwa** [comment]
can i work on this?

**Comment by BOLT04** [comment]
@VictoryWekwa yes, I can assign this issue to you since I don't think anyone is working on it 😃

**Comment by eddiejaoude** [comment]
Great, thanks @VictoryWekwa 👍
