### ISSUE TITLE
How to join our organization

### ISSUE THREAD

**Issue by AllanRegush** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#35]
I think the should be a section on the website on how to join.

**Comment by BOLT04** [comment]
Do you think this should be below our mission statement or the projects list? I think we can prioritize the most important sections to be first for better UX, but the "how to join" section seems to fit in FAQ (it would probably the most frequent).

What do you think of this being implemented like discussed in #7 @AllanRegush?

**Comment by eddiejaoude** [comment]
Oh this is a great idea 👍 . FAQs are usually towards the end of the page. I guess things can be moved around later too

**Comment by AllanRegush** [comment]
I think it would work okay in a FAQ section. But I was just thinking about making it easier for someone wanting to join. Maybe have a join section after the projects?

**Comment by Arvindjitta** [comment]
> I think the should be a section on the website on how to join.

still i'm not sure how to join ..can anyone explain how

**Comment by eddiejaoude** [comment]
@Arvindjitta raise an issue on this repo asking to join and I will add you https://github.com/EddieJaoudeCommunity/support/issues

**Comment by eddiejaoude** [comment]
@AllanRegush ok good idea, lets make it stand out even more 👍

**Comment by BOLT04** [comment]
@AllanRegush thanks for clarifying, I understand your point of view now. I totally agree with your idea 😃.
We can even have a button after projects saying "Join the community" or just "Join"...although it might not be clear for the user what that button does with just "Join" 🤔. Then with a GitHub action, this joining process that Eddie does manually gets automated 😮 😮😮 😄 

@eddiejaoude do you think this can be done easily, or does it require more work to automate the joining process? If it's harder, simplifying is better, imo, so we could add a section like @AllanRegush suggested.

**Comment by eddiejaoude** [comment]
It seems like there is a GitHub Action we can use to do this #137, so maybe a message and a button might be enough
