### ISSUE TITLE
Open discussion for the community website 

### ISSUE THREAD

**Issue by gagangaur** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#4]
here in this issue drop ideas regarding design, technology stack, new feature regarding the community website.

**Comment by eddiejaoude** [comment]
Probably best to have an `issue` for each topic, otherwise it will get too busy/noisy in a single `issue`. We can discuss this on the live stream 🤓

**Comment by alrifay** [comment]
@eddiejaoude should we close this issue ?

**Comment by eddiejaoude** [comment]
Yes I think this has been superseded now with new issues that are specific. Thanks @alrifay
