### ISSUE TITLE
Slight typo on newcomers.md 

### ISSUE THREAD

**Issue by mikeysan** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#42]
In [newcomers.md](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/develop/NEWCOMERS.md)

We have the following entry: "Now you can go ahead and effect the desired changes."

I think this should read: " Now you can go ahead and affect the desired changes."

i.e. affect instead of effect.

**Comment by eddiejaoude** [comment]
Fixed https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/pull/43
