### ISSUE TITLE
Should the image on our readme.md link to something else

### ISSUE THREAD

**Issue by mikeysan** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#44]
At the moment when you click on the community image on [EJC](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io) it opens a new tap with a larger image. 

Might it be a good idea to make that image link to something more useful instead? Maybe something like the newly created newcomers.md?

**Comment by eddiejaoude** [comment]
Good idea 👍

**Comment by Obizim** [comment]
I can take this up but where exactly should the image link to?
The newcomers.MD or where?

**Comment by mikeysan** [comment]
I think newcomers.md is a good start. It can always be changed later once implemented.

**Comment by alrifay** [comment]
This issue could be `good first issue`, what do you think @eddiejaoude ?

**Comment by BOLT04** [comment]
@alrifay I agree 😃. Right now the image doesn't take you anywhere when clicked, so for the issue, the list of tasks could be:
- [ ] Wrap the [image](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/c05edc301ea4e552bda93f00cbee0b98cd3d2851/src/App.svelte#L12) with an `<a>` tag and add the `href` attribute with the value: https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/develop/NEWCOMERS.md
- [ ] Add the `target="_blank"` attribute to the anchor tag to open in a new tab

**Comment by eddiejaoude** [comment]
Sounds good 👍

**Comment by Sumit-Sahu** [comment]
Can I work on this??

**Comment by BOLT04** [comment]
sure @Sumit-Sahu 👍

**Comment by eddiejaoude** [comment]
PR #102 was merged
