### ISSUE TITLE
Missing link in readme.md, typo in contributing.md and newcomers.md

### ISSUE THREAD

**Issue by UdokaVrede** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#45]
The images below highlight the areas affected.
![ok](https://user-images.githubusercontent.com/63649352/91972806-1d4d7b00-ed13-11ea-9cc3-756955059cf5.png)
![no](https://user-images.githubusercontent.com/63649352/91972811-1e7ea800-ed13-11ea-90a2-6677fdc9750d.png)
![not](https://user-images.githubusercontent.com/63649352/91972815-20486b80-ed13-11ea-85c2-9a26e62838be.png)

**Comment by eddiejaoude** [comment]
Oh good spot 👍

**Comment by UdokaVrede** [comment]
I'd fix this now but on the readme.md I noticed this 
![no](https://user-images.githubusercontent.com/63649352/91973745-a913d700-ed14-11ea-9913-343b6cb7af53.png)
please what is meant to be here

**Comment by eddiejaoude** [comment]
Another great spot 👍 , these are still work in progress, so thank you for moving it forwards 🤓 

this is meant to be the list of repos we, their description and tech - but for now, even a list of repos is a big improvement 👍 , link to the repo list https://github.com/EddieJaoudeCommunity

**Comment by UdokaVrede** [comment]
This should be done in a tabular format right?
like repositories, description and technologies?

**Comment by eddiejaoude** [comment]
I think tabular would be better 👍 , but a list is ok for now too, up to you 🤓

**Comment by eddiejaoude** [comment]
I will close this Issue as PR #46 got merged. Can you raise a new issue for the project list?
