### ISSUE TITLE
Also to include on the website

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#5]
New issues should be created for each feature below...

- Code of Conduct
- why join our community
- Connect with us on:
   - Discord
   - GitHub Organisation
   - Live streams
   - Support repo
- Profile picture on these platforms
   - Its more friendly
   - Could be a pet or cartoon character, default pictures look like bots or spam
- our project/repo list, technologies, state (alpha, beta, ...)
- join our GitHub organisation

**Comment by gagangaur** [comment]
we can probably have a nav at the top of landing page referring to different pages of the website like to 
> connect us
> about community (here we can show the list of members of the community)


and will post some ideas later.

**Comment by alrifay** [comment]
is this issue resolved? 🤔

**Comment by BOLT04** [comment]
I think most bullet points are done @alrifay. Although I don't think we have the COC on the footer.
I think originally @gagangaur created a PR to change the Envato image on the website and add a navigation bar, but that isn't completed yet.
@eddiejaoude what do you think about closing this issue?

**Comment by eddiejaoude** [comment]
Thank you @alrifay and @BOLT04 , yes lets close this and we can make new more specific issues as required 👍
