### ISSUE TITLE
Adding links to Github repos

### ISSUE THREAD

**Issue by RemcoHalman** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#52]
Would it be an idea to add links to the [Community website](https://eddiejaoudecommunity.github.io/) cards?

For example the _Hacktoberfest practice_ to the repo [Hacktoberfest practice](https://github.com/EddieJaoudeCommunity/hacktoberfest-practice)

**Comment by eddiejaoude** [comment]
Yep good idea @RemcoHalman  👍

**Comment by Obizim** [comment]
I think this is a nice idea too. Maybe an eye icon or "view repo" text on each card that will link to the project repo on click

**Comment by RemcoHalman** [comment]
I could do this today 👍

**Comment by eddiejaoude** [comment]
@Obizim oh I like it 👍 .

Thanks @RemcoHalman that would be amazing. Let me assign it to you 🤓

**Comment by eddiejaoude** [comment]
@RemcoHalman the icon could come in another Issue and PR, it doesn't all have to come together - just an idea

**Comment by alrifay** [comment]
@eddiejaoude i think its already done in PR https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/pull/39

**Comment by eddiejaoude** [comment]
@alrifay thank you for noticing, you are right! 👍 . It didn't get merged to `main` yet so it was not deploy, I am doing that now in #53

**Comment by eddiejaoude** [comment]
Deployed 👍 .

@RemcoHalman please have a look, see if there are any improvements you recommend. If not, we can close this.

**Comment by RemcoHalman** [comment]
I don't think so, that solved the linking off the cards. Personally I would wrap it in a link `<a>` with a text. What do you all think? Or else ill let it be just like this




> Maybe an eye icon or "view repo" text
