### ISSUE TITLE
Add Community GitHub Action to this repo

### ISSUE THREAD

**Issue by AakarshTeja** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#55]
This is the community Action https://github.com/EddieJaoudeCommunity/gh-action-community

And here is an example of how to add it https://github.com/EddieJaoudeCommunity/support/blob/main/.github/workflows/community.yml

**Comment by BOLT04** [comment]
For reference, this is related to the issue #50

**Comment by iambami** [comment]
Can I take this?

**Comment by AllanRegush** [comment]
@iambami Yep it's free. I'll assign it to you.

**Comment by VictoryWekwa** [comment]
Hello, Is this issue still open?

**Comment by iambami** [comment]
Hi I'm no the project. Haven't been with my laptop for a while. Sorry Vikky😁

**Comment by AllanRegush** [comment]
closed by PR #88

**Comment by VictoryWekwa** [comment]
> Hi I'm on the project. Haven't been with my laptop for a while. Sorry Vikky😁

Oh.. okay.. Great.
