### ISSUE TITLE
Who are the Moderators

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#6]
Who to contact if there is an issue, please do not tag these people for general tech questions

**Comment by BOLT04** [comment]
@eddiejaoude I have a question about how to implement this issue. I was going to make this in a new file called `moderators.html`, which would be a new page that the user could navigate to with the navbar above. Is it easier to instead put the code on `index.html`?
If the navbar gets merged before this, I'll update it, but the list of moderators could be on `index.html` and provide value immediately when it gets merged.

What do you think should be done?

**Comment by eddiejaoude** [comment]
>  Is it easier to instead put the code on index.html

yes, I think having it in the `index.html` for the now is easier, we can move it out later if needed

Thanks @BOLT04 , we were chatting in Discord earlier today about using the [horizontal cards](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/pull/21) for the moderators and the [vertical cards](https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/pull/24) for the projects - both have PRs. What do you think?

**Comment by BOLT04** [comment]
ahh cool, I didn't catch the whole discussion on the UI for those cards, thanks for letting me know @eddiejaoude 😃. I think using those horizontal cards you mentioned is great. I haven't had much time this week to continue development on this issue, but tomorrow I'll continue and make a PR.

I'll contact Rvindjitta to align on the code he has for these cards and what I have.

**Comment by eddiejaoude** [comment]
> I didn't catch the whole discussion on the UI for those cards

Dont worry, that is why I prefer having the main points of the chat on GitHub because in Discord things get lost / missed easily

Yeah I think chat and align with @Arvindjitta , the screenshot in PR #21 is out of date, and he has done more work on it. PR #24 got merged, but still needs more work to it, for example tech stacks and links to repos etc
