### ISSUE TITLE
Add back the spacing to Projects section

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#75]
## Description
I noticed on our deployed version of the website we have a margin of 8: https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/01c27e5fd2d8227395a6c7b1ff36fcb1a7eb458f/index.html#L47

**Screenshot (main branch)**
![imagem](https://user-images.githubusercontent.com/18630253/94375110-26125080-0109-11eb-9064-725c2f5fcd7d.png)

**Screenshot (develop branch)**
![imagem](https://user-images.githubusercontent.com/18630253/94375121-3cb8a780-0109-11eb-9ea5-d412c19ae558.png)

## Solution
We can simply add the `mb-8` class back, it probably got lost on some PR. Here is the line to change: https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/blob/598649ef1bae144e99c944c76b4e36dd3a372a01/src/App.svelte#L86

**Comment by eddiejaoude** [comment]
Thanks @BOLT04 👍

**Comment by iambami** [comment]
love to take this

**Comment by AllanRegush** [comment]
@iambami Assigning to you.

**Comment by iambami** [comment]
Thanks Allan. Can I have the bring down of the issue, please?

**Comment by alrifay** [comment]
It's already fixed in #83, I didn't notice that we have an issue for it 😅

**Comment by BOLT04** [comment]
sorry @iambami, it was indeed done on that PR @alrifay mentioned. I'll close this issue but there are other issues you can work on if you want 😃
