### ISSUE TITLE
Consider using a tool to analyse the website (e.g. performance, accessibility)

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#86]
Recently I heard of this GitHub action called [Lighthouse Check](https://github.com/marketplace/actions/lighthouse-check) and I think we can use it to start analyzing our website and see if there is anything we can improve 😃.

Every time a PR opens we could check if performance dropped or SEO went up because of X change (e.g. by adding [good alt attributes](https://moz.com/learn/seo/alt-text)).

What does everyone think?

**Comment by vamsi963601** [comment]
Does it provide any visual aids?

**Comment by BOLT04** [comment]
yes @vamsi963601 😃, it has this table after the action runs:
![imagem](https://user-images.githubusercontent.com/18630253/94992340-50d52c80-0581-11eb-9cfe-0bb84936e687.png)

But we can also download the artifact and use the HTML page to see the results:
![imagem](https://user-images.githubusercontent.com/18630253/94992352-621e3900-0581-11eb-8c01-42ed7a9bd7aa.png)

**Comment by BOLT04** [comment]
I ran lighthouse on our current deployed version and I think some points can be improved, for example:
![imagem](https://user-images.githubusercontent.com/18630253/94992460-14ee9700-0582-11eb-9cf4-0723c17fedfb.png)

These are those badges on each moderator card like "community" or "python". Perhaps they should have be a `label` HTML element and not a button. Semantically they are just labels, imo. If not I think the Lighthouse's suggestion of adding more space between each button is helpful on mobile as well 😃

**Comment by eddiejaoude** [comment]
Yes 💪 and even more awesome if we can run it as a GitHub Action too 👍

**Comment by AllanRegush** [comment]
I found about this tool this week. Was going to mention it :+1:

**Comment by BOLT04** [comment]
I'd like to work on this 😃, is someone already working on it?

**Comment by eddiejaoude** [comment]
I am just working through notifications. I assigned it to you, but looks like you created a PR already 👍 . I will get to it shortly 🤓
