### ISSUE TITLE
Adding New branch

### ISSUE THREAD

**Issue by RemcoHalman** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#89]
@eddiejaoude @BOLT04 I rebuild the community page in VueJS to showcase the difference. Can a branch be added to the GH before i do a pull request?

**Comment by BOLT04** [comment]
@RemcoHalman sure 👍. I'll call it `vuejs` and it will be created from `develop` (currently in Svelte). Then when you create the PR, set the target branch to `vuejs` 😃

**Comment by RemcoHalman** [comment]
@BOLT04 Awesome just got the cypress changed to run with the app.

**Comment by eddiejaoude** [comment]
Thanks @RemcoHalman and @BOLT04 👍
