### ISSUE TITLE
Chore: add eslint & prettier config

### ISSUE THREAD

**Issue by AllanRegush** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#93]
We are now using javascript for this project. It might be a good time to add some tools.
Should we keep the same code style as EddieBot?

**Comment by Jashpatel1** [comment]
If the issue is open, I would like to take it. @AllanRegush

**Comment by AllanRegush** [comment]
All yours @Jashpatel1. Assigning to you.
