### ISSUE TITLE
Add a note on README for multiple tech branches (e.g. Vue.js)

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#97]
We have the `develop` branch built with Svelte, but recently @RemcoHalman contributed with a Vue.js version. We should add a notice on the README so people are aware these branches are for some "display" purposes and to compare 😃

**Comment by eddiejaoude** [comment]
Yep 👍 . I will add the label `good first issue`

**Comment by VictoryWekwa** [comment]
Hello, Is this issue still open?

If yes, can it be assigned to me?

**Comment by eddiejaoude** [comment]
Sure @VictoryWekwa 👍

**Comment by VictoryWekwa** [comment]
Hello @eddiejaoude i just created a PR. Please kindly review and let me know if i need to add any other information.
